version: '3.9'

networks:
  jobboard-network:
    driver: bridge
    name: jobboard-network

volumes:
  redis-data:
    name: jobboard_redis-data

services:

  redis:
    build:
      context: ./docker/redis
      dockerfile:
        Dockerfile
    restart: always
    platform: linux/amd64
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf", "--appendonly", "yes" ]
    ports:
      - "6379:6379"
    networks:
      - jobboard-network
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf:cached
      - redis-data:/data:delegated