name: CI Workflow

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  backend-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install npm
      run: npm install -g npm@9.5.0

    - name: Copy project files
      run: |
        mkdir -p usr/app &&  cp backend/package.json backend/package-lock.json usr/app
        cp -r backend/* usr/app

    - name: Install dependencies
      run: npm ci
      working-directory: usr/app

    - name: Run tests
      run: npm run test
      working-directory: usr/app
